ktor:
  application:
    modules:
      - io.spektacle.ApplicationKt.module
  deployment:
    port: 8080
db:
  url: 'jdbc:postgresql://localhost:5432/ebookmanager'
  username: 'postgres'
  password: 'admin'
  maxPoolSize: 3